spring:
  profiles:
    active: default
  mvc:
    throw-exception-if-no-handler-found: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jakduknoreply
    password: q1w2e3r$
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 10MB

jakduk:
  remember-me-seed: 2f76392e-8b1d-4beb-aca0-b7f53a010e0c
  api-url-path:
    user-picture-large: user/picture
    user-picture-small: user/picture/small
    gallery-image: gallery
    gallery-thumbnail: gallery/thumbnail
